### ISSUE TITLE
Unable to create strategy or add exchange on mac

### ISSUE THREAD

**Issue by jaisontj** [GimmerBot/Gimmer#1]
I have successfully signed in (The eth address is the same as the one which received the GMR tokens)
But I am unable to create a strat or add an exchange
Kindly advice on  what needs to be done.

Creating a bot says: "cannot read property name of null"
and trying to add an exchange says : "cannot read property toString of undefined."

I have tried deleting my account and trying again.

I am on a mac running High Sierra 10.13.4
Gimmer bot version: 0.2.1

**Comment by Flllexa** [comment]
@jaisontj This bug is happening because of the certificates.
We are already building a new version with this fix.

If you are still experiencing this issue, try to whitelist Gimmer App on your firewall or antivirus.
Let us know if this fix temporaly the problem until the next update.

**Comment by jaisontj** [comment]
I do not have an antivirus running and my firewall is turned off. Same problem persists. Is there an ETA on when the new version will be released?

**Comment by jaisontj** [comment]
Any ETA on when this will be released? I tried out v0.2.11 and this problem persists.

**Comment by rafagimmer** [comment]
Hello @jaisontj.
I'm use Gimmer on MAC. Can you send one print of the error, please?
Tks

**Comment by jaisontj** [comment]
Hey, this is the error I receive when trying to add a strategy
<img width="1204" alt="screen shot 2018-06-22 at 2 48 04 am" src="https://user-images.githubusercontent.com/13097323/41746086-c44decd0-75c6-11e8-94a6-60344d151c12.png">

**Comment by Illustratum** [comment]
Yes, same here.

Version 1.5.0

**Comment by Illustratum** [comment]
Reboot Computer worked.

**Comment by oly99** [comment]
im getting Cannot read property 'total' of null  when trying to add my api  for coinbase   and for binance
is there a fix for this

**Comment by jaisontj** [comment]
Hey, looks like no one has addressed this yet. One of the reasons why this was happening was because the exchange (one of them) had blocked my region for API access. Using a VPN and trying worked.
