### ISSUE TITLE
Showing wrong buy price in live mode

### ISSUE THREAD

**Issue by johnyqi** [GimmerBot/Gimmer#100]
#### Expected Behaviour
Buy price should be equal as the one on the exchange
#### Actual Behaviour
Gimmer shows price which is usually few percents higher from the actual purchase price which can be seen on Binance. In this particular case, I bought ICX for 2.02, while Gimmer shows that buy price was 2.06.
#### Steps to Reproduce the Problem
On every buy
#### Specifications
 - Gimmer Version: 0.2.14
 - OS: OSX
 - Date: 16.6
 
#### Printscreen (Case needed)
<img width="571" alt="screenshot 2018-06-16 09 42 28" src="https://user-images.githubusercontent.com/36193495/41496881-28dd91fe-714a-11e8-9524-f103c91f27fc.png">

**Comment by Flllexa** [comment]
It was fixed in 1.8.6 version
