### ISSUE TITLE
Unable to open bot

### ISSUE THREAD

**Issue by Crypto-Ferret** [GimmerBot/Gimmer#106]
#### Expected Behaviour
Create Bot
#### Actual Behaviour
Can not read property 'name' of null agreeing to T7C
#### Steps to Reproduce the Problem
Create bot and custom Name 
#### Specifications
 - Gimmer Version: 0.3
 - OS: win 10 x64
 - Date: 22/06/2018

#### Printscreen (Case needed)
![name null](https://user-images.githubusercontent.com/39388970/41772078-282731ba-760f-11e8-8abd-72fd9e85813b.JPG)

**Comment by Flllexa** [comment]
This bug was fixed asking to uninstall, after, restart your pc, and then install again. 

Tks Ferret
