### ISSUE TITLE
Gimmer freezes and log you out when trying to run new strategy

### ISSUE THREAD

**Issue by znoc40** [GimmerBot/Gimmer#107]
#### Expected Behaviour
I create a new strategy, I save it and then I click on RUNNING & ACTIVITY, with test mode on . The running &activity window should show and you can start running the bot in test mode.

#### Actual Behaviour
The progress bar goes from left to right, slows down at the end and stays there.
After a minute or so the app logs you out.
If you login again you find yourself in the running & activity window and you can start the simulation.

#### Specifications
 - Gimmer Version: 0.3.0
 - OS: Ubuntu 16.04
 - Date: 24 June 2018

**Comment by Flllexa** [comment]
It was fixed in 1.7.7 version
