### ISSUE TITLE
Bitfinex not executing trades

### ISSUE THREAD

**Issue by Crypto-Ferret** [GimmerBot/Gimmer#109]
#### Expected Behaviour
Buy and sell orders should execute on Bitfinex
#### Actual Behaviour
Buy and sell orders not executing in live trading
#### Steps to Reproduce the Problem
N/a
#### Specifications
 - Gimmer Version: 0.3
 - OS: win 10 x64
 - Date: 27-28/06/2018
 
#### Printscreen (Case needed)
![bb settings](https://user-images.githubusercontent.com/39388970/42018540-5779d900-7aaa-11e8-8cde-2242ac405b0f.JPG)
![bifinex backtest](https://user-images.githubusercontent.com/39388970/42018541-57940f46-7aaa-11e8-9138-5f5a9dd9e1ac.JPG)
above is the backtest results
![bitfinex live](https://user-images.githubusercontent.com/39388970/42018542-57aef126-7aaa-11e8-9eac-dd919e3f26b2.JPG)
above is the Live trading activity screen

**Comment by Crypto-Ferret** [comment]
[error.log](https://github.com/GimmerBot/Gimmer/files/2170656/error.log)

**Comment by muzkle** [comment]
Ok, i just noticed on the log file that your API for bitfinex has the wrong permissions, that's why it didn't triggered the orders, please check:

This API key does not have permission for this action

**Comment by Crypto-Ferret** [comment]
![api permissons](https://user-images.githubusercontent.com/39388970/42381790-1bdf533a-812a-11e8-9037-8dce69be5235.JPG)

**Comment by Crypto-Ferret** [comment]
Yes my mistake

**Comment by Crypto-Ferret** [comment]
Forgive my stupidity....

**Comment by muzkle** [comment]
Exactly, in order for this API to work correctly, you must check orders and wallets in the "Write" permissions.
