### ISSUE TITLE
Can't start 1.0 on Mac

### ISSUE THREAD

**Issue by johnyqi** [GimmerBot/Gimmer#110]
I deleted the old version, but still unable to run it.

<img width="411" alt="screenshot 2018-07-11 15 14 01" src="https://user-images.githubusercontent.com/36193495/42580486-f8bd9470-852a-11e8-983f-430802000626.png">
<img width="1237" alt="screenshot 2018-07-11 15 15 10" src="https://user-images.githubusercontent.com/36193495/42580487-f8dc09c8-852a-11e8-8fbc-725b12988794.png">

**Comment by Flllexa** [comment]
You are very fast man, I replaced this version, you need download and install again.
