### ISSUE TITLE
Can't add Binance API

### ISSUE THREAD

**Issue by johnyqi** [GimmerBot/Gimmer#114]
<img width="701" alt="screenshot 2018-07-11 18 22 46" src="https://user-images.githubusercontent.com/36193495/42586073-8043379a-8537-11e8-9ea9-79e65c993e02.png">

OSX

**Comment by johnyqi** [comment]
Its working now, no idea why :-)

**Comment by Illustratum** [comment]
Never worked for me :P wait two days like you did? xD

Hope it works!
