### ISSUE TITLE
Suggestion: Delayed Buy / Sell signal

### ISSUE THREAD

**Issue by johnyqi** [GimmerBot/Gimmer#115]
Case: When we want to catch the bottom, often it happens that after indicators react on the signal and execute the trade, the price continues to drop. Would be nice if the trigger would have a delay option. So for example if we are trading 1 minute chart, delay would be additional 30 seconds. If price at that point moved further down, bot wouldn’t buy, if price starts to move up, bot would execute trade. Basically bot would delay purchase as long reverse is not confirmed. This is specially useful for RSI which often goes into overbought position and stays there for several candles more.

**Comment by Flllexa** [comment]
You can change this setting in profile.
