### ISSUE TITLE
Prevent bot going into trade right after Stop Loss

### ISSUE THREAD

**Issue by johnyqi** [GimmerBot/Gimmer#117]
Bot tends to go into a trade right after Stop Loss is triggered because indicator conditions are still present, although the price is dropping. Solution would be to ignore indicators until the next alignment. Or maybe simply put a time freeze, let's say 5 candles before bot goes into trade again.

**Comment by Flllexa** [comment]
It was added in 1.7.7 version, its the pit-stop
