### ISSUE TITLE
Error installing v1.01

### ISSUE THREAD

**Issue by Crypto-Ferret** [GimmerBot/Gimmer#118]
#### Specifications
 - Gimmer Version:
 - OS:
 - Date:
 
#### Printscreen (Case needed)
[SquirrelSetup.log](https://github.com/GimmerBot/Gimmer/files/2216067/SquirrelSetup.log)

**Comment by Flllexa** [comment]
This error occurs when the user tries to run the setup twice ... the installer takes to start, then the user click in setup again.
