### ISSUE TITLE
XRP charts not loading beyond May 4.

### ISSUE THREAD

**Issue by johnyqi** [GimmerBot/Gimmer#12]
<img width="1516" alt="screenshot 2018-05-16 21 07 11" src="https://user-images.githubusercontent.com/36193495/40138534-379b2efa-594d-11e8-9cfe-d91529323f67.png">
I'm unable to load chart prior 4. May 2018. Other coins seems fine.

**Comment by lucasassislar** [comment]
https://www.reddit.com/r/Ripple/comments/8gxobh/binance_adds_xrpusdt_pair_finally/
If I'm correct, the USD/XRP coin pair only exists in Binance after May 5th as it was introduced to the exchange then.
I'm closing this issue as it seems like just a misunderstanding, if you keep experiencing any problems just forward it to us ^^.
