### ISSUE TITLE
Unable to add exchange on mac

### ISSUE THREAD

**Issue by TarsisiusLePrepus** [GimmerBot/Gimmer#123]
#### Expected Behaviour

Can add an exchange.

#### Actual Behaviour

Can't add exchange (Binance)!

#### Steps to Reproduce the Problem

Just to add an exchange.

#### Specifications
 - Gimmer Version: 1.7.6
 - OS: Mac
 - Date: January 27 2019
 
#### Printscreen (Case needed)
![error gimmer](https://user-images.githubusercontent.com/31491498/51808403-5da86580-2261-11e9-867d-307729e51ad4.png)

**Comment by wheatdogg** [comment]
I have the same problem, but with 1.7.8 for Linux
Gimmer version: 1.7.8
OS: Ubuntu 16.04 LTS (from .deb package)
Date: Feb 12, 2019

**Comment by EduMenges** [comment]
Same issue, but on Windows 10 version 1.7.9.

**Comment by Flllexa** [comment]
It was fixed in 1.8.6 version
