### ISSUE TITLE
Simulation Broken - Stop Loss

### ISSUE THREAD

**Issue by luchocala** [GimmerBot/Gimmer#130]
#### Actual Behaviour

The backtest shows incorrect info. For example, if the system buys at the price of 100, and then it has to sell it to 103, it shows stop loss 3%, and negative profit". This doesnt happen in previous versions.

#### Steps to Reproduce the Problem

Create a strategy with stop loss and test it. The problem should appear.

#### Specifications
 - Gimmer Version: 2.1
 - OS:
 - Date:

**Comment by Flllexa** [comment]
Do you can retry in last version and send me the config for us test here?

https://github.com/GimmerBot/Gimmer/releases/tag/v2.1.121

**Comment by Flllexa** [comment]
Is ok in current version.
