### ISSUE TITLE
Keeps loading eternally.

### ISSUE THREAD

**Issue by luchocala** [GimmerBot/Gimmer#131]
#### Expected Behaviour

Normal Functionality.

#### Actual Behaviour

Gimmer symbol of loading keeps in the screen forever. This happens after login, navigating into different sections of the app, and when saving. Random bug.

#### Specifications
 - Gimmer Version: 2.1 and later
 - OS: Windows 7
 - Date: April 9th 2020

**Comment by Flllexa** [comment]
Sorry, we released a new version with this problem fixed, tks
