### ISSUE TITLE
Volume indicator missing on code editor

### ISSUE THREAD

**Issue by luchocala** [GimmerBot/Gimmer#132]
#### Expected Behaviour

Missing volume indicator for code editor. I think this is a very important indicator and i cant find ot on the list.

The volume indicator i am suggesting is the default volume indicator in trading view with the MA of 20

#### Actual Behaviour

Indicator missing.

#### Specifications
 - Gimmer Version:
 - OS:
 - Date:

**Comment by Flllexa** [comment]
You have in context the volume to use in your code.

Has many indicators to work using the volume:
https://tulipindicators.org/list

![image](https://user-images.githubusercontent.com/5155989/79290379-53907800-7ea2-11ea-8610-4b0fc26c9a1e.png)
![image](https://user-images.githubusercontent.com/5155989/79290232-eed51d80-7ea1-11ea-80dd-73f32e4c219a.png)

**Comment by Flllexa** [comment]
I added the prints how can use the volume in code editor
