### ISSUE TITLE
Cannot read property 'words' of undefined

### ISSUE THREAD

**Issue by luchocala** [GimmerBot/Gimmer#133]
#### Expected Behaviour

Normal Login.

#### Actual Behaviour

When trying to login, an error appears: Cannot read property 'words' of undefined

#### Steps to Reproduce the Problem

Try to login. Sometimes happens, sometimes not.

#### Specifications
 - Gimmer Version: 2.1.118 and newer.
 - OS:
 - Date:

**Comment by nastyatimosha** [comment]
yes i have the same problem!!! please fix it!! urgently!!! i wrote many messages in the chat on the website but 3 days nobody answer there!

**Comment by nastyatimosha** [comment]
also when i was logged in.. i had problem that i cannot add my exchange.. when i click on my exchanges it shows only the searching tool but it does nothing.. very slow to load

**Comment by nastyatimosha** [comment]
i downloaded older versions but problem remains

**Comment by Flllexa** [comment]
We published a dedicated blockchain server and fixed this problem. Tks by report
