### ISSUE TITLE
Different interval for safeties

### ISSUE THREAD

**Issue by johnyqi** [GimmerBot/Gimmer#15]
Although this option was present in the demo, somehow in beta we are unable to set a different interval for safeties.

**Comment by modem7** [comment]
This was a feature in the demo - surely it's a regression rather than feature request @Flllexa?

**Comment by Flllexa** [comment]
It's confuse for many users, the safety keep active in real trading and for backtest too, but is manage by system now, you need only select the safety and set the settings in own safety

**Comment by modem7** [comment]
They aren't acting rapidly enough. What values does the system use? Is it dynamic?

**Comment by Flllexa** [comment]
For livebots is checked by minute and backtest the safety follow the period. But I think that is better add advanced options and leave that advanced users configure this parameters.

**Comment by modem7** [comment]
@Flllexa Maybe add a "Default: 60 sec" option as well for people who just want whatever the system default was

**Comment by Flllexa** [comment]
The problem is the backtest, if we leave sefety with 60 sec for backtest and the user set a 1 day for period, is very slow, because is checked minute by minute, but the solution that I said help, is the union from 2 solutions, using the system by default and leave a advanced panel.

**Comment by modem7** [comment]
I don't disagree, but remember that there's a warning of how long things
could take + there's also the stop button as well.

Either way would work quite well!

**Comment by johnyqi** [comment]
hmm, in that case, the backtest will always perform slightly worse because safety is fixed? Not ideal, I would say. It will be hard to judge the real performance of the backtest.

**Comment by modem7** [comment]
@Flllexa - for now, let's go with your idea - it seems solid, and probably would sort many of the backtest accuracy results we're getting
