### ISSUE TITLE
[0.2.1] Margin Trading on Exchanges

### ISSUE THREAD

**Issue by modem7** [GimmerBot/Gimmer#21]
As far as I'm aware, Binance does not support Margin Trading as of yet. It might be worthwhile removing the Binance (and maybe other exchanges who don't support it) from the supported exchanges under that particular bot.

**Comment by rafagimmer** [comment]
@modem7, 
At this time, the margin-trade, is also disabled from the Gimmer. It will go into operation later. Even because, we need to pass more details of the features and risks to the beginning traders.
thank you.
