### ISSUE TITLE
[0.2.1] Binance Error Code While Strategy Is Running Live 

### ISSUE THREAD

**Issue by samsonite11** [GimmerBot/Gimmer#22]
Expected Behaviour: The strategy should be buying and selling. The simulation works but not the real thing.

Actual Behaviour: The strategy constantly produces the following error (as shown in screengrab).

To reproduce this problem: API was created on Binance, and a market exchange strategy with a 1 min period was created and ran.

Gimmer version: 0.2.1 
OS: Mac High Sierra 10.13.4
Date: 17/5/18

<img width="310" alt="screen shot 2018-05-17 at 7 57 50 am" src="https://user-images.githubusercontent.com/39352406/40149032-9d727708-59b4-11e8-9e34-21a79033edec.png">

**Comment by rafagimmer** [comment]
Hi samsonite11,
I'm trying to simulate what you reported, did you ever use any gauge? If so, give me the information so I can run your scenario exactly and give you a more concrete solution.

**Comment by samsonite11** [comment]
Hi Rafa, 

I’m not sure what you mean by a gauge but here is everything I did:

Strat Settings:

Mode:
- Trade

Order:
- Market

Exchange:
- Binance

Base:
- ETH

Quote:
- BTC

Period:
- 1M

API: Binance API

Indicator Setup (See image 1)

Stop Loss: 25

And then I just ran it.

Could it be something to do with the API rules that Binance sets?

Hope you can fix it!

Kind Regards,

Sam

**Comment by rafagimmer** [comment]
I created a bot with the same settings as yours and am waiting for the purchase time to see if the same error occurs for me. I'll talk to you again.

Best regards

**Comment by samsonite11** [comment]
Thank you, any luck?

**Comment by altcoinrockerxyz** [comment]
Hello samsonite and rafagimmer,

I am encountering the same problem and found the same issue resolved on another github. Apparently with the example, a parameter name was not set correctly. For more details, please refer to the following link: 

https://github.com/sammchardy/python-binance/issues/112

So I am guessing the problem may have to do with the Binance API integration codes that are hardcoded in the Beta app.

I'm looking forward to this getting resolved.

All the best!

**Comment by johnyqi** [comment]
I have the same error, and I think this is what causes absence of trades in live bot.

**Comment by Flllexa** [comment]
Fixed in 0.2.11 version. Tks guys!

**Comment by samsonite11** [comment]
The same error occurred even after updating to 0.2.11
