### ISSUE TITLE
Incorrect stats

### ISSUE THREAD

**Issue by johnyqi** [GimmerBot/Gimmer#23]
I have 5 live bots, not a single trade, but stats are showing various percentages. Shouldn't all be on zero?
<img width="1850" alt="screenshot 2018-05-17 07 50 08" src="https://user-images.githubusercontent.com/36193495/40158899-22d5af54-59a7-11e8-89d5-f6a53a39d63a.png">

**Comment by marciorcruz** [comment]
Error in the analysis of the percentage of performance in the same exchange.

**Comment by lucasassislar** [comment]
Hello jonyqi!
As soon as you start a live bot, it immediately starts calculating how much have you lost/won by just holding (until an actual trade comes through).

Also, for this current Beta version we highly recommend you keep Live Bots to a minimum, as there might be conflicts when running multiple bots on the same account.
