### ISSUE TITLE
Strategy Keep Running Even When Stopped

### ISSUE THREAD

**Issue by altcoinrockerxyz** [GimmerBot/Gimmer#24]
Gimmer version: 0.2.1
OS: Mac High Sierra 10.13.4

So I'm having error -1104 while running [Exchange Trading bot using Ichi Cloud via Binance API](https://github.com/GimmerBot/Gimmer/issues/22).

Due to this, I decided to stop the bot from executing. It did stop, but after a short while, it starts running again -- so I'm guessing it is a bug.

**Comment by IlkkaE** [comment]
Gimmer version: 0.2.11
Os; Windows 10

Same thing running binance bot using bnb/usdt MACD via Binance API.

![4](https://user-images.githubusercontent.com/39367604/40269609-7cf1d2b8-5b89-11e8-940a-ca0c11c9b94e.PNG)

 Closing gimmer and opening it again won't make a difference. When you open gimmer again, it looks like the strategy is already running.

![3](https://user-images.githubusercontent.com/39367604/40269651-23fcf93e-5b8a-11e8-8989-489b8365014f.PNG)

Also after installing 0.2.11 after deleting the whole content of gimmer install folder and generating new API keys, Gimmer shows usdt balance from two days ago (then 114usdt, should be 98 usdt).

All in all, API implementation needs a lot of love atm. Keep up the good work! You can do it! :)

**Comment by Flllexa** [comment]
It has been fixed
