### ISSUE TITLE
indicator request ADX

### ISSUE THREAD

**Issue by swampibboy** [GimmerBot/Gimmer#26]
would be nice to see the ADX indicator in the final release

https://www.investopedia.com/terms/a/adx.asp

**Comment by Flllexa** [comment]
We have in our code editor, but need to know TypeScript, I added some Open Sources to be a base.
https://github.com/GimmerBot/Gimmer
![image](https://user-images.githubusercontent.com/5155989/77005104-07075a80-693f-11ea-8ad2-9d1648be69df.png)

![image](https://user-images.githubusercontent.com/5155989/77004793-79c40600-693e-11ea-942a-6734dabea61d.png)
