### ISSUE TITLE
Add exchange fees to backtest

### ISSUE THREAD

**Issue by swampibboy** [GimmerBot/Gimmer#29]
adding the exchange fees into the back test will make it clearer if a strategy is profitable when scalping

**Comment by johnyqi** [comment]
Would be lovely.

**Comment by swampibboy** [comment]
100%
i can not use the indicators as they are to create a scalping bot as i can not read the 100's of trades to calculate if the individual profits would actually be profits when the fees are deducted!

**Comment by swampibboy** [comment]
.1% in .1% out so .2% a trade, but when scalping you might be closing on .12%  but fees are .2% so is a loss but would read as a win !

**Comment by modem7** [comment]
https://support.binance.com/hc/en-us/articles/115000429332-Fee-Structure-on-Binance

**Comment by johnyqi** [comment]
Ah yea, I was thinking, if profit is 1%, then 10% of that (0.1) would go for fees.

So for example, you buy 100 dollars (fee is 0.1) and sell 101 dollars (fee is 0.101). So profit is 1 dollar - minus 0.201 for fees, so around .80? Actually, quite a lot if we are doing scalping. So Gimmer would have to calculate the fee for each trade and add them up.

**Comment by altcoinrockerxyz** [comment]
Ah I kinda posted a feature request similar to this one at https://github.com/GimmerBot/Gimmer/issues/44

**Comment by johnyqi** [comment]
Maybe there is a simple tweak for this issue, until team builds something better. How about marking profitable trades, which are below 0.20%, with yellow, but not green? That way we would have a quick visual how many trades are on the border of loss, because of trading fees.

**Comment by keithfawcett** [comment]
+1 I really need to see actual profits, which means deducting fees in backtesting.

**Comment by Flllexa** [comment]
Gimmer already have the exchange fee and its used in backtests
