### ISSUE TITLE
Stopping the bot opens a error message (+no trades during test 12h)

### ISSUE THREAD

**Issue by IlkkaE** [GimmerBot/Gimmer#30]
**Expected Behaviour: **1.**** The bot should stop without any error messages. **2.** There should have been at least one trade during test perioid (the gauge went to 100% buy).
**Actual Behaviour: **1.**** When trading in Binance stopping the bot retuns this error message. **2.** No trades occured druring test (12H)
Os: Windows 10
Gimmer version: 0.2.1
Date: 17/5/18
#![img_20180517_071353](https://user-images.githubusercontent.com/39367604/40165710-5c41dba0-59c5-11e8-85ca-0cad9c0c0336.jpg)

**Comment by Flllexa** [comment]
This problem is with Binance only, already was reported before, we are fixing and we will upload an release with this correction today yet.

Tks

**Comment by IlkkaE** [comment]
No problem, just trying to help to squash those nasty bugs. Keep up the
good work!

Ilkka E.

to 17. toukok. 2018 klo 15.52 Persio Flexa <notifications@github.com>
kirjoitti:

**Comment by Flllexa** [comment]
Implemented in 0.2.11 version. Tks!
