### ISSUE TITLE
Indicators do not work correctly!!!!URGENT

### ISSUE THREAD

**Issue by swampibboy** [GimmerBot/Gimmer#31]
The indicators do not work as well as they should.
As a simple example using a common, two moving averages indicator over a 1 year period and setting the chart to 1 day candles the chart reads very smoothly and the peaks and troughs can easily be read.
Now adding a fast 50 MA and a slow 200MA the buy and sell signals are very clear an are just where you expect them to be on a chart.
Now when this is loaded into the gimme back test the results are very different and very out of line with what is within the expected range of the return of profit.
I can not figure out for the life of me why this is so out of kilter , i have tried and tried to get the settings to mirror what would happen if i were day trading using indicators and it just won't work.
Please can you advise us

**Comment by johnyqi** [comment]
Have to confirm this. I’m not professional trader, but I can definitely see that there is a distortion between what indicator shows visually, and what bot actually does.

**Comment by swampibboy** [comment]
no im sure its the way the indicators are configured within the gimmer programme its self.

**Comment by SheMaster** [comment]
Yes, difficult to check reaponsibility box if trades are off in dapp itself. Please make this work.

**Comment by mike197930** [comment]
Concur on all of above

**Comment by modem7** [comment]
@Flllexa @marciorcruz - this should be labelled bug, not discussion.

**Comment by swampibboy** [comment]
thanks mate, i'll get the hang of this one day!
and yes @Flllexa @marciorcruz this is so urgent please fix the indicators

**Comment by swampibboy** [comment]
WOW, still labelled a discussion!!!...yet with no discussion from the dev's .

**Comment by lucasassislar** [comment]
Hello!
This issue has been noticed by the dev team and we are currently working on updating the application to better respond. We're sprinting through major issues and this should be fixed in a few releases.

**Comment by swampibboy** [comment]
excellent news!!

**Comment by Flllexa** [comment]
Hello man, I updated the principal indicators, and I will calibrate yet macd. I wait that you like, I'll upload the new version soon, but the problem with indicators, sentiment and binance is solved.

Tks by your support ;)
