### ISSUE TITLE
Trigger failure

### ISSUE THREAD

**Issue by tntxtra** [GimmerBot/Gimmer#33]
I am in bittrex and have a trigger issue. even though the sentiment and the 3 indicator bars on top shift to 100% buy with the perfect conditions in the established parameters, the buy is not executed.... I was monitoring all indicators live at the same time and waited for the trade to happen it never did... it was a perfect buy opportunity.

windows
beta 2.1
rsi/ema/stoch    all green  no buy

**Comment by swampibboy** [comment]
any chance you could share a screen grab ? @tntxtra

**Comment by lucasassislar** [comment]
Hey @tntxtra !
To help us reproduce this can you describe your bot settings/post a screenshot? 
Also, did your account on Bittrex register anything at all on the API logs?

Any further information could greatly help we solve your issue.

**Comment by Flllexa** [comment]
For the bot buy or sell, you need to have asset in base or quote of the pair, need to have minimum assets that the Exchange stipulated for trades. We already comproved that the bot buy and sell.

Thank you!!
