### ISSUE TITLE
MACD is configured wrong for maximum gains

### ISSUE THREAD

**Issue by swampibboy** [GimmerBot/Gimmer#34]
Linux chrx 4.9.4-galliumos-braswell #1 SMP PREEMPT galliumos2 Thu Feb 23 01:58:04 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

 Order type
market
 Exchange
Binance
 Base
bnb
 Quote
Usdt
time interval
6 hr 

From

04/20/2018 01:02
To

05/18/2018 01:02

default MACD settings

Fast period

12
 Slow period

26
 Signal period

9
 Invert signal
[N]

![image](https://user-images.githubusercontent.com/30175655/40211727-cc2d217e-5a3b-11e8-8e50-2dbaab5feeff.png)
This is a sample to show how the MACD indicator has not been configered to its fullest abillity . all the Buy/Sell's have been marked on the chart with a blue line. You can clearly see that each buy or sell signal is triggered when the slow period line crosses the zero line. the red lines marked on the chart indicate where the slow and fast period lines cross and is where the buy/sell signals should be triggered for maximum gains.
there are many more case for all the indicators in  #31

**Comment by swampibboy** [comment]
still getting the same signals in 0.2.1 as i am in the newer 0.2.11,
gimmer is triggered when the slow ema crosses the zero line and not when the fast crosses the slow or the slow crosses the fast!!

**Comment by swampibboy** [comment]
please look at fixing the indicators please as they are the engine of the platform and with out them the platform is redundant !

**Comment by swampibboy** [comment]
@marciorcruz @lucasassislar @Flllexa @muzkle
We can confirm that this is not an exchange/api related bug but is platform wide , leading us to believe that it is indeed the macd's buy/sell parameters are set.
hope that helps

**Comment by znoc40** [comment]
While you're at it, it would be highly recommended to add thresholds (up and down) to the signal crossing to make sure the crossing is a real trend.
As an example, if you set a 0.025 up and a -0.025 down threshold, the buy trigger should be given when the macd (26-12) crosses upwards the signal line (9) +0.025, and a sell trigger should be given when macd crosses downward the signal line minus 0.025.
I attach the parameters you can set in gekko, as an example.
I did several backtests and the influence of the thresholds is really key: setting them to zero (so buying and selling exactly on signal line crossing) would bring the profit down from 89% over 3 months to 10% only.
![screenshot from 2018-06-02 16-17-40](https://user-images.githubusercontent.com/39218727/40877918-ecc0d49a-6688-11e8-84b0-8a9f31303f7c.png)

**Comment by Flllexa** [comment]
We separate customized settings and default, now if want run with Gimmer settings you need enable on checkbox, tks guys
