### ISSUE TITLE
Stochastic indicator not working

### ISSUE THREAD

**Issue by swampibboy** [GimmerBot/Gimmer#35]
Linux chrx 4.9.4-galliumos-braswell #1 SMP PREEMPT galliumos2 Thu Feb 23 01:58:04 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Order type
market
Exchange
Binance
Base
bnb
Quote
Usdt
time interval
6 hr

Stochastic indicator
gimmer default settings

![image](https://user-images.githubusercontent.com/30175655/40213689-4e98b59c-5a46-11e8-90fc-1c03e0ac25c1.png)

The correct buy and sell signals are marked on the chart with green lines, as hard as i have tried i can not figure out why gimmers Stochastic indicator is making buy and sell signals the way it is but as you can clearly see it is not how a Stochastic indicator should work at all.

**Comment by Flllexa** [comment]
I leave the indicator standard equals tradingview and separated a customized attribute for the user enable if want, but is not present in this new version yet, I'll leave open this issue for continue the improvements, tks man
