### ISSUE TITLE
Problem with tradingview chart and trade history

### ISSUE THREAD

**Issue by Drangla** [GimmerBot/Gimmer#36]
TV Chart:
![tv2](https://user-images.githubusercontent.com/35429030/40225006-31f49fae-5a88-11e8-9855-9c1010ac3419.jpg)
Gimmer Chart:
![tv1](https://user-images.githubusercontent.com/35429030/40224993-28324426-5a88-11e8-9a94-fb36c71fec1e.jpg)
and trades are not displayed:
![g2](https://user-images.githubusercontent.com/35429030/40225103-72c237bc-5a88-11e8-93b2-fdd1e64e3dba.jpg)
![g3](https://user-images.githubusercontent.com/35429030/40225146-8c4f00b6-5a88-11e8-81fc-6b8d15cb4643.jpg)

**Comment by johnyqi** [comment]
I think this is because Gimmer gets data only at certain intervals, therefore chart looks choppy. They told me it will be fixed soon.

**Comment by Flllexa** [comment]
It was fixed
