### ISSUE TITLE
After Crash accounts are gone

### ISSUE THREAD

**Issue by AndreasTTT** [GimmerBot/Gimmer#37]
after a crash, no more accounts are displayed

Windows 10 (64bit)

**Comment by AndreasTTT** [comment]
excuse my inaccuracy
has not directly to do with gimmer but
my windows 10 has crashed and thereby became
after the reboot (no windows repair in any form necessary)
No more accounts left and had to start with zero again

**Comment by lucasassislar** [comment]
@AndreasTTT It's possible your PC bluescreening corrupted the application's db, but we'll investigate to make sure that's the case (and if there's anything we could have done to make sure those accounts were saved).
Thanks for the feedback
