### ISSUE TITLE
EMA convergence/divergence settings to loose or off

### ISSUE THREAD

**Issue by swampibboy** [GimmerBot/Gimmer#39]
Linux chrx 4.9.4-galliumos-braswell #1 SMP PREEMPT galliumos2 Thu Feb 23 01:58:04 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Order type
market
Exchange
Binance
Base
bnb
Quote
Usdt
time interval
6 hr

From

04/20/2018 01:02
To

05/18/2018 01:02

default MACD settings

Fast period

9
Slow period

26

Invert signal
[N]

![image](https://user-images.githubusercontent.com/30175655/40231594-3a11e158-5a8b-11e8-9e3f-3b1ae39b276b.png)

as you can see the signals are plotted by tradingview and are marked with a blue + 70% of the buy sell triggers from Gimmer are with in tolerance but the other 30% ether do not fire or are hugely out of tolerance!

**Comment by Flllexa** [comment]
Hi, we already fixed the dapp and will upload the release 0.2.12 soon, tks
