### ISSUE TITLE
Updating database From wrong exchange.

### ISSUE THREAD

**Issue by Crypto-Ferret** [GimmerBot/Gimmer#40]
Expected Behavior: Trade between LTC/USDT on Bitfinex
Actual Behavior: Database updates with BNB/USDT from binance database
Steps to Reproduce the Problem Live trade on Bitfinex with same pairing?
Specifications
Gimmer Version: 0.2.1
OS: Win 10 x64
Date: 18/05/2018 23:33
![gimmer bug 18052018 23_33](https://user-images.githubusercontent.com/39388970/40260733-239a5a72-5af4-11e8-8566-c5157df814cc.JPG)
As

**Comment by modem7** [comment]
Make sure to click "save" each time, it seems the current expected behaviour is that nothing will actively change until you click save each time

**Comment by Crypto-Ferret** [comment]
@modem7 Hi thanks for responding, I am aware I need to press save to ensure all changes are confirmed and in this case, I had done just that. I have also deleted the api and created a new key, but the bot fails to even load any information in this panel now. (screen grab will follow shortly)
Thanks

**Comment by modem7** [comment]
Cool, just making sure you hadn't done exactly what I did! :-D

**Comment by Flllexa** [comment]
The bot in live running is immutable, you need stop and start again for run a bot with other configurations.

**Comment by Crypto-Ferret** [comment]
Thank you for the update
