### ISSUE TITLE
Binance API clock syncing issue

### ISSUE THREAD

**Issue by IlkkaE** [GimmerBot/Gimmer#41]
**Expected Behavior:** 
1. When new version of Gimmer is installed on top of the old one, Gimmer should accept clock settings if they are updating automaticly on the computer where the dapp is installed.

**Actual Behavior:**
**1.**  Dapp gives clock syncing error message when looking at api keys settings. The clock is off by 10000ms. As a result (???) dapp gives error message about incorrect api keys when trying to start live strategy.
 
**Steps to Reproduce the Problem:**
**1.** Install new version of Gimmer on top of old version and look at binance exchange api keys setup page on the app.
!!! Both errors can be corrected by the user temporarely(?) by turning automatic date and time settings off and then back on. !!!

**Specifications:**
**Gimmer Version:** 0.211
**OS:** Windows 10
**Date:** 19.5.5018

**Comment by modem7** [comment]
Personally, I would get the time from an NTP server rather than from a user's local machine. This would be a better usage, more accurate and less likely to be skewed

**Comment by Flllexa** [comment]
Hi, Binance updated your API, we already updated the dapp and will release soon, tks
