### ISSUE TITLE
A Way to Project % Gains

### ISSUE THREAD

**Issue by altcoinrockerxyz** [GimmerBot/Gimmer#44]
Hello,

This is a feature request to have a way of knowing how much % would be gained if one is to use a trading bot for any pair. This could be a way to point out the High and Low prices and compute how much is the difference between the two and what would be the % profit if one is to buy at the average lows and sell at the average highs no matter what trading period is used.

In this way, one may be able to see whether the gains are good enough to cover the trading fees.

All the best!

**Comment by altcoinrockerxyz** [comment]
This is pretty much related to the issue https://github.com/GimmerBot/Gimmer/issues/29

**Comment by swampibboy** [comment]
would this be a historical feed for projections ?

**Comment by altcoinrockerxyz** [comment]
Hello @swampibboy,

I assume it may need historical feed to base the maximum high and low prices depending on how wide is the span and how many periods it will cover. 

On the other hand, it could also just accept a % profit the user wants to gain, and the bot will auto-compute how that condition could be fulfilled before placing buy/sell orders. SO say I want to have a 10% gain for every trade, the bot will compute the best time to place a buy order (based on whatever indicator is being used) and then once the buy order is filled, it will auto-compute which price to sell to get 10% profit.

**Comment by swampibboy** [comment]
Hello @altcoinrockerxyz .

 Thank you for clarifying that point for m. Within other bot trading platforms this feature is implemented via a nodejs. code and I see no reason why it could not be implemented into the gimmer ecosystem via the code editor when/if it is implemented !!

Regards  Brian

ETA , on a side note if your are on Telegram , could you please reach out to me @Cypherdyne_Systems to discuss this more. 
Many thanks
