### ISSUE TITLE
No version number

### ISSUE THREAD

**Issue by IlkkaE** [GimmerBot/Gimmer#45]
Expected Behavior
![5](https://user-images.githubusercontent.com/39367604/40269828-080169b6-5b8c-11e8-8b8d-e31fe8e77aab.PNG)

Actual Behavior:
![2](https://user-images.githubusercontent.com/39367604/40269808-d2e01bec-5b8b-11e8-9e0e-fc18c6f8d40d.PNG)

Steps to Reproduce the Problem:
Install clean version of 2.11 (delete manually all contents of gimmer folder). After rebooting Gimmer the version number was correct.
Specifications
Gimmer Version: 2.11
OS: Windows 10
Date: 19.5

**Comment by Flllexa** [comment]
Tks man, it's was fixed in 0.2.12 version. 👌
