### ISSUE TITLE
Live trading still not working

### ISSUE THREAD

**Issue by johnyqi** [GimmerBot/Gimmer#46]
I have the latest, v0.211, and after several hours of testing, 15 minutes bots, I'm still not getting any trades.

Is there are a way to generate log files? That might help you to detect the problem.

Mac OS
Binance

**Comment by Crypto-Ferret** [comment]
I to have failed to have any successful trades on Binance or Bitfinex, But would like to point that I have had a successful seel order execute on bittrex

**Comment by samsonite11** [comment]
I am also still having this error even after updating to 0.2.11. I get an error in addition to trades not executing... #52 #22

**Comment by Flllexa** [comment]
Hi, Binance updated your API, we already fixed the dapp and will upload the release 0.2.12 soon, tks
