### ISSUE TITLE
Gimmer as a service - Linux

### ISSUE THREAD

**Issue by modem7** [GimmerBot/Gimmer#48]
Is it possible to integrate the Linux client so that it can run as a service, with the front end available via a web browser? 

This would enable us to more easily have a bot running 24/7 on a (headless) server, and the ability to change settings without having a GUI desktop if we have so chosen to run our setups like that.

**Comment by Flllexa** [comment]
It's currently not in our plans to provide a server version of the application for end users, but you're free to run the current version for yourselve anywhere.

We will offer Gimmer on VMs as a service for our users very soon (scheduled for Q3 2018).
https://token.gimmer.net/#roadmap
