### ISSUE TITLE
UI/UX problem

### ISSUE THREAD

**Issue by IlkkaE** [GimmerBot/Gimmer#49]
**Expected Behavior**
Clicking edit button on the first indicator on the left should open just one window

**Actual Behavior**
Dapp opens first two windows on the left and you cannot edit the first one because the second is on top of it.
![sieppaa](https://user-images.githubusercontent.com/39367604/40271966-f4eddb8a-5bad-11e8-8bc8-69ac1679fdaa.PNG)

**Steps to Reproduce the Problem**
Make strategy with 4 indicators and try to edit the first one on the left
Specifications: Screen resolution 1366x768

**Gimmer Version:** 0.2.11
**OS:** Windows 10
**Date:** 19.05.2018

**Comment by muzkle** [comment]
Hi @IlkkaE ,
This problem has been fixed as it was a problem also related to this issue #62 .
Expected to be working on the next release.
Thanks for your support.
