### ISSUE TITLE
[0.2.0] Gimmer installed in unusual location in Windows

### ISSUE THREAD

**Issue by modem7** [GimmerBot/Gimmer#5]
Gimmer version 0.2.0 Windows 7 x64

Gimmer is installed by default in C:\Users\user\AppData\Local\gimmer

Should realistically be installed in C:\Program Files or similar. 

Have also noticed that the entry under all programs is "Persio Flexa". Might be worthwhile changing this to "Gimmer" to avoid issues later. 

![capture](https://user-images.githubusercontent.com/4349962/40137956-8a4dd8a0-5943-11e8-92c0-a15f61e8afdf.JPG)

**Comment by modem7** [comment]
As an additional idea, it might be worthwhile having the settings (wherever they are locally stored) to be stored separately from the program itself. This would allow easier backups, easier updates, easier log finding and easier sharing of data pre-marketplace

**Comment by Flllexa** [comment]
Sorry, the dapp get the author and create this folder, I fixed in 0.2.11 version. Tks!
