### ISSUE TITLE
RSI parameters for buys and sells seems to be reversed 

### ISSUE THREAD

**Issue by tntxtra** [GimmerBot/Gimmer#51]
![xrp rsi a](https://user-images.githubusercontent.com/33947294/40273338-890b9824-5b8c-11e8-9627-d8a4c5c4538a.png)

As we can see the buys are triggered at high rsi points and the sells are triggered at low rsi parameters. that is completely reversed. If we can get gimmer to look at he parameters the correct way that would be a start.

windows/ 2.1.1/ rsi/ live

**Comment by Flllexa** [comment]
RSI was fixed now, is disponible in new version 0.2.14, thanks
