### ISSUE TITLE
[0.2.11] Binance Error Code While Strategy Is Running Live - Cont.

### ISSUE THREAD

**Issue by samsonite11** [GimmerBot/Gimmer#52]
Updated to 0.2.11 and I receive the same error.

Settings are the exact same as the closed issue #22 

<img width="267" alt="screen shot 2018-05-20 at 9 45 13 am" src="https://user-images.githubusercontent.com/39352406/40274139-c81de6a8-5c12-11e8-9d43-4c482d397bbe.png">

**Comment by Flllexa** [comment]
Hi, Binance updated your API, we already updated the dapp and will upload the release 0.2.12 soon, tks
