### ISSUE TITLE
Impossible to build a strategy 

### ISSUE THREAD

**Issue by swampibboy** [GimmerBot/Gimmer#53]
Using the current indicators and there faulty setting, it is aparent that we will not be able to build any strategies that will work as they should or even safely.
this issue is true for all OS's.
PLEASE i implore you to fix the indicators first! this is of the upmost importance, with out them the platform is useless!!!
@Flllexa 
#50 
#51 
#27 
#31

**Comment by lucasassislar** [comment]
Hello @swampibboy !
From the time the oldest issue in our server (#1 ) till now 2 work days have passed, we've just begun adjusting to getting feedback from Github and are working intensively on verifying and making sure that all bugs are fixed for the next version.

Thanks for the feedback so far
