### ISSUE TITLE
Log box issue

### ISSUE THREAD

**Issue by Crypto-Ferret** [GimmerBot/Gimmer#54]
The log box of the bots I am running keep clearing after I leave the activity page.
It would be much better to have information here at all times so that I can check the bot is pulling data from the correct sources. 
(this is especially important during this beta testing stage)
Please could we adjust this asap, as this data will help me to help you.

Thanks

**Comment by Flllexa** [comment]
The complete logs you can found in %APPDATA%/gimmerbot/logs

I can`t show all, because is a lot information, and now, Gimmer has high frequency.
