### ISSUE TITLE
Incorrect buy/sell sentiment

### ISSUE THREAD

**Issue by Crypto-Ferret** [GimmerBot/Gimmer#56]
When entering the activity pane of two of the live bots I noticed the Buy/sell sentiment bar at the top reading a strong buy point. 
If you look at the below screen grabs you can see the indicator overlay for the EMA cross with correct parameters reading a sell indicator cross on both.
Fortunately neither bot at this time has exectued a trade but I think this is more to do with the api issues you are experencing than the bot being aware it should sell instead of buy.
![binance gnt_eth sentiment error](https://user-images.githubusercontent.com/39388970/40415358-96c7b8f6-5e72-11e8-8aa9-e4fecf84daa5.JPG)
![sentiment issues bittrex](https://user-images.githubusercontent.com/39388970/40415359-96e68f42-5e72-11e8-90db-f1c2c9141576.JPG)

**Comment by Flllexa** [comment]
I calibrate the indicators and is equals the tradingview indicators now, the Binance is fixed, the Binance updated the API, is the next update and I will release soon. 

Tks
