### ISSUE TITLE
Show trade values with more decimals for non-fiat currencies in Simulation History

### ISSUE THREAD

**Issue by keithfawcett** [GimmerBot/Gimmer#57]
Expected Behavior - See more decimals for trade values in history
Actual Behavior - History only shows 0.00
Steps to Reproduce the Problem - View history on "Running & Activity" after running a simulation.
Specifications
Gimmer Version: v0.2.11 - v0.2.12
OS: Windows 7
Date: 05/26/2018

Could the history show trade values with more decimals for non-fiat currencies? Currently I'm only seeing 0.00, instead of something like 0.000079

![image](https://user-images.githubusercontent.com/592055/40581515-c6dec0b2-6128-11e8-8981-5d36f49a90b5.png)

**Comment by muzkle** [comment]
Hi @keithfawcett ,
This issue has been fixed and you can see on the image below and will be available on our next release.
Once you test it, let us know.

Thanks for your support!

![buy-sell-fix](https://user-images.githubusercontent.com/16977637/40628273-646b8c30-629a-11e8-8f6f-29f4fbe5ed10.PNG)

**Comment by Flllexa** [comment]
Thank you Keith, you help a lot ;)
