### ISSUE TITLE
Specify the start balance for the simulations

### ISSUE THREAD

**Issue by keithfawcett** [GimmerBot/Gimmer#59]
Expected Behavior - Set balance for simulation
Actual Behavior - Balance defaults to 500 BTC
Steps to Reproduce the Problem - Start Simulation
Specifications
Gimmer Version: v0.2.11 - v0.2.12
OS: Windows 7
Date: 05/26/2018

Could we specify the start balance for the simulations? It's defaulting to 500 BTC, which is not a realistic amount for most of us.

![image](https://user-images.githubusercontent.com/592055/40581525-22089332-6129-11e8-8199-fd62c952d878.png)

**Comment by modem7** [comment]
![capture](https://user-images.githubusercontent.com/4349962/40582008-1ee73532-6160-11e8-9304-dd521447e38f.JPG)

You can change this by editing the above

**Comment by keithfawcett** [comment]
@modem7 you don't have that option on the "Running & Activity" view.

**Comment by modem7** [comment]
I stand corrected!

**Comment by modem7** [comment]
@keithfawcett Give me a shout on telegram @sasha105 - we have a small group of people doing Gimmer beta testing if you'd like to join us

**Comment by muzkle** [comment]
You need to make sure the bot is stopped, change the amount on the field explained from @modem7 and save, after the strategy completely changed and saved, you can start your simulation within the new start balance.

**Comment by keithfawcett** [comment]
@muzkle Please see this video. Your instructions do not change the issue. 

https://youtu.be/eueSY6bqjsc

**Comment by muzkle** [comment]
Just noticed your message and checked this video, you're right, it is not applying to the simulation, but to the backtest only. I have reopened this issue and will fix this. Thanks.

**Comment by Flllexa** [comment]
Hello, in version 2.0.212 we already added this function, download the last version to check it.
