### ISSUE TITLE
Beta version bug reporting feature

### ISSUE THREAD

**Issue by modem7** [GimmerBot/Gimmer#6]
Add a bug reporting feature in Gimmer Beta that would allow people to more easily post issues to git/gimmer bug reporting servers. 

Many people are unfamiliar with how Git works, and this feature would allow further bug reporting to be made, more accurately, with potential of additional logs attached as well.

**Comment by IlkkaE** [comment]
Better debuggin tools are needed, if possible. There's no way atm. to see what happens under the hood.

**Comment by modem7** [comment]
I had a further idea rather than making a central bug reporting server. An export of logs we can post to git would probably be easier to develop in shorter time

**Comment by modem7** [comment]
Have moved onto other projects. Closing this unless someone requires this functionality.
