### ISSUE TITLE
Correct non-fiat trading pair prices

### ISSUE THREAD

**Issue by keithfawcett** [GimmerBot/Gimmer#60]
UPDATE: This appears to be a bigger issue than initially understood or something changed in v0.2.13. Non-fiat trading pairs do not work in simulation (e.g. NEO/BTC, ETH/BTC, etc.) due to prices showing as 0.00 instead of something like 0.00000804.

Expected Behavior - See prices on right of graph
Actual Behavior - prices are cut off
Steps to Reproduce the Problem - View ETH graph or CVC graph
Specifications
Gimmer Version: v0.2.11 - v0.2.12
OS: Windows 7
Date: 05/26/2018
 
Could the TradingView graph be adjusted to show the prices on the right? For some reason it's being cut off.

![image](https://user-images.githubusercontent.com/592055/40581538-6574c4b0-6129-11e8-9f6e-ea1ef4787008.png)

**Comment by muzkle** [comment]
Hi @keithfawcett , the log scale is dinamically builded from tradingview.
I have noted the same issue, but i was able to find the values by clicking and draging down the scale as you can see on my picture below. So this isn't a bug, but the lack of price action to make the log scale visible.

BTW, i didn't saw the same behavior on ETH/BTC if that's the one you mentioned.
![cvc-binance](https://user-images.githubusercontent.com/16977637/40626427-e6f5a796-628e-11e8-988a-a8fd2236cb6d.PNG)

**Comment by muzkle** [comment]
BTW, i've noted that the chart is not loading the complete history from Binance. I'll be checking that.

**Comment by keithfawcett** [comment]
I think this is like the issue we had in the history section where there are not enough deicmals. It appears that more decimals are needed. 

Here's inside Gimmer
![image](https://user-images.githubusercontent.com/592055/40810977-7ac8b11e-64fd-11e8-8a59-be65e2551059.png)

Here's the same chart in Tradingview showing many more decimals.
![image](https://user-images.githubusercontent.com/592055/40811101-f78e29e0-64fd-11e8-91e4-ec0a1458d908.png)

**Comment by keithfawcett** [comment]
It actually looks like any non-fiat pairs are incorrect in decimals now. Not sure if something changed between v0.2.12 and v0.2.13. All crypto pairs only show 2 decimals places (0.00) instead of 8 decimal places (0.00000000).

**Comment by keithfawcett** [comment]
Here is a screenshot showing TRX/BTC. It should have mutltiple buy/sells, but none are being created. It appears this is due to price being 0.00 instead of prices with more decimal places, so there's no way to buy. 

0.00 - 0.00 = 0
0.00000804 - 0.00000404 = 0.00000400

![image](https://user-images.githubusercontent.com/592055/40813642-ea891924-6509-11e8-9835-580de67e6593.png)

Here's a fiat currency crypto pair, since it only needs two decimals to have non-zero values, it's creating buys/sells.

![image](https://user-images.githubusercontent.com/592055/40813679-24ad2938-650a-11e8-96b7-5046ae0ee7c8.png)

**Comment by muzkle** [comment]
This has been fixed and will be available on the next update, check the image below:

![values](https://user-images.githubusercontent.com/16977637/41628778-81cc4044-73fc-11e8-88fd-d332a386b9c9.PNG)
