### ISSUE TITLE
[Improvement] Have popup boxes in line with GUI

### ISSUE THREAD

**Issue by modem7** [GimmerBot/Gimmer#61]
As one can see, the popup boxes are not skinned the same as the general GUI. Improvement  required to bring in line.

![capture](https://user-images.githubusercontent.com/4349962/40581998-d90e569e-615f-11e8-92d5-c36e22f93328.JPG)

![capture](https://user-images.githubusercontent.com/4349962/40582045-58a70fc6-6161-11e8-920b-1f31d1d489f2.JPG)
![capture2](https://user-images.githubusercontent.com/4349962/40582046-58c49a6e-6161-11e8-9669-9ab43c502108.JPG)

Also, spelling error, should be "stopped" instead of "stoped"

**Comment by Flllexa** [comment]
It was improved
