### ISSUE TITLE
Unable to close Indicator panel by clicking outside of panel.

### ISSUE THREAD

**Issue by keithfawcett** [GimmerBot/Gimmer#62]
Expected Behavior - Panel should close when clicked outside of panel area
Actual Behavior - Panel stays open
Steps to Reproduce the Problem - 
1. Add indicator to test
2. Click Pencil icon
3. Click outside of Panel
Specifications
Gimmer Version: v0.2.11 - v0.2.12
OS: Windows 7
Date: 05/27/2018

Once an indicator has been selected and you edit the values, the panel does not close when clicked outside of panel or by reclicking the Pencil icon. The only way I'm able to close it is by clicking on the Configuration, Indicators, or Safeties menu items.

![image](https://user-images.githubusercontent.com/592055/40582331-db6be182-6140-11e8-88df-f3a221cb4de1.png)

**Comment by muzkle** [comment]
@keithfawcett I'll be labeling this as improvement, as it closes but there's one spot where it does not close itself. Thanks for finding this issue.

**Comment by keithfawcett** [comment]
@muzkle I think this is more a bug, than improvement. If you click the Pencil Icon to open the menu, at a minimum, you should be able to click the Pencil icon to close the menu. That does not work. 

Ideally, you should also be able to close it by clicking anywhere outside of the menu. You could call the click outside of the menu an improvement, but it's fairly standard UX design. 

See this video for better understanding: https://youtu.be/uEXquvoJI5s

**Comment by muzkle** [comment]
You can't close it by clicking anywhere?

**Comment by keithfawcett** [comment]
Clicking the Pencil icon only opens. 
Second click on the Pencil icon does not close menu.
Clicking outside of menu does not close menu.

**Comment by muzkle** [comment]
@keithfawcett This issue have been fixed and will be updated with our next release.
Once you test it again with the new version, update this issue to let us know ok?
Thanks for your support.

**Comment by keithfawcett** [comment]
Will do, thanks!

**Comment by keithfawcett** [comment]
This is now working! Thanks.
