### ISSUE TITLE
RSI buy/sells are incorrect.

### ISSUE THREAD

**Issue by keithfawcett** [GimmerBot/Gimmer#65]
Expected Behavior: Attached screenshot should only have sell orders. The RSI indicator never made it below the threshold for buys. 
Actual Behavior: Multiple buy and sell orders were created.
Steps to Reproduce the Problem

1. Select BITTREX:CVCBTC
2. Backtest with 5 minute interval
3. Add RSI indicator
Time period = 14
High level = 67
Low level = 32
4. Run test

Specifications
Gimmer Version: v0.2.11
OS: Windows 7
Date: 05/27/2018

![image](https://user-images.githubusercontent.com/592055/40591479-1947e92a-61e0-11e8-9427-764f00c1f287.png)

**Comment by muzkle** [comment]
Hi @keithfawcett,
@Flllexa is now improving all the indicators and making sure everything works as expected.

**Comment by Flllexa** [comment]
RSI was fixed now, is disponible in new version 0.2.14, thanks
