### ISSUE TITLE
MACD Signals are incorrect

### ISSUE THREAD

**Issue by keithfawcett** [GimmerBot/Gimmer#66]
Expected Behavior: Buy should only happen when Blue crosses above Red. Sell should only happen when Blue crossed below red.
Actual Behavior: Buys and sells are happening in other places.
Steps to Reproduce the Problem:

Specifications
Gimmer Version: v0.2.12
OS: Windows 7
Date: 05/27/2018

![image](https://user-images.githubusercontent.com/592055/40596404-7dcb7506-6208-11e8-85f2-97eaaf3c024d.png)

**Comment by muzkle** [comment]
Hi @keithfawcett,
@Flllexa is now improving all the indicators and making sure everything works as expected.

**Comment by Flllexa** [comment]
We separate customized settings and default, now if want run with Gimmer settings you need enable on checkbox, thank you Keith
