### ISSUE TITLE
Buy indicator is showing, but no buy happened

### ISSUE THREAD

**Issue by keithfawcett** [GimmerBot/Gimmer#67]
Expected Behavior: There should not be a buy on chart since there was no blue crossing above red during the timeframe.
Actual Behavior: A buy indicator is showing
Steps to Reproduce the Problem:
Specifications
Gimmer Version: v0.2.12
OS: Windows 7
Date: 05/25/2018

![image](https://user-images.githubusercontent.com/592055/40596559-b3c8b10e-6209-11e8-9c2e-d8518f3d5d2a.png)

**Comment by muzkle** [comment]
Hi @keithfawcett,
@Flllexa is now improving all the indicators and making sure everything works as expected.

**Comment by keithfawcett** [comment]
Was this fixed in v1.0?

**Comment by Flllexa** [comment]
In the new version we have advanced the roadmap, some items may have already solved this problem for you.

Send me your configuration so I can test here.

**Comment by Flllexa** [comment]
It was fixed
