### ISSUE TITLE
Invert Signals looks like it is backwards for all indicators

### ISSUE THREAD

**Issue by keithfawcett** [GimmerBot/Gimmer#68]
Expected Behavior: Indicators should function normally without needing to select "Invert Signal"
Actual Behavior: Signals are inverted while "Invert Signal" is not selected. In other words, it appears that Sells are happening when buys should happen and buys are happening when sells should happen. 
Steps to Reproduce the Problem: Setup a test, add an indicator (e.g. EMA Cross), run test. Then add EMA cross on Trading View chart and compare. 
Specifications
Gimmer Version: v0.2.12
OS: Windows 7
Date: 5/28/2018

![image](https://user-images.githubusercontent.com/592055/40597093-3f14af44-620d-11e8-8c9c-9b326b99f2b3.png)
#51

**Comment by modem7** [comment]
Issue is still occurring with BB on 0.2.13

**Comment by Flllexa** [comment]
Ema is not inverted, is ok, but you can check the checkbox invert signal.

Thanks

**Comment by keithfawcett** [comment]
Please reopen this until all Indicators are correct. I.e. don't need "Invert Signal" selected in order to function properly.
