### ISSUE TITLE
i think the RSI indicator does not work properly (BETA 0.212)

### ISSUE THREAD

**Issue by Drangla** [GimmerBot/Gimmer#70]
EOS/BTC
Bitfinex
30min Candles 
RSI: Lenght 14, Low Level 30, High Level 70
I think the Bot is buying and selling only above the High Level (70) instead of buying at 30 and selling at 70:
![unbenannt](https://user-images.githubusercontent.com/35429030/40620350-c987a7f4-6298-11e8-90b3-96a4772afb53.PNG)

**Comment by Drangla** [comment]
Maybe i just messed up my settings, i dont know, im not an professional trader :-)
another example:
![unbenannt2](https://user-images.githubusercontent.com/35429030/40620631-d29b655a-6299-11e8-973c-779883537fd7.PNG)

**Comment by modem7** [comment]
What happens if you invert the signal?

**Comment by Drangla** [comment]
buys and sells at the low level

**Comment by Flllexa** [comment]
RSI we need improve yet, we improve HMA, EMA, STOCH and BOLLINGER BANDS

**Comment by Drangla** [comment]
ah ok, thx for the info !!

**Comment by swampibboy** [comment]
buy/sell triggers only occur in one zone rather than the opposite zones .e.g buys when signal line moves out of the 80 index , then sells as it crosses back into the 80 index.
It should buy when moves down out of the 20 index and the hold until it move up out of the 80 index @Flllexa

**Comment by Flllexa** [comment]
We fixed the RSI indicator to buy in bottom and sell in top. Tks
