### ISSUE TITLE
Stochastic Oscillator buy/sells are incorrect.

### ISSUE THREAD

**Issue by keithfawcett** [GimmerBot/Gimmer#71]
Expected Behavior: Buy should only happen when signal crosses above oversold threshold (i.e. 20). Sell should only happen when signal crosses below overbought threshold (i.e. 80). 
Actual Behavior: Tons of buys and sells are showing with no clear pattern of why.
Steps to Reproduce the Problem: Add Stochastic Oscillator and run backtest. 
Specifications
Gimmer Version: v0.2.12
OS: Windows 7
Date: 5/28/2018

Here's an example of when the buys and sells should happen.
![image](https://user-images.githubusercontent.com/592055/40627637-163c7f3a-628e-11e8-8058-54aaec4c1906.png)

Here's a screenshot of Gimmer.
![image](https://user-images.githubusercontent.com/592055/40627800-1fba5bd0-628f-11e8-93ea-f882af9545b1.png)

**Comment by keithfawcett** [comment]
Was this fixed in v1.0?

**Comment by Flllexa** [comment]
Hello man, we fixed it, I cant remember the version... but is only download the last version, is necessary enable the movement check equals the image bellow:

https://github.com/GimmerBot/Gimmer/releases

![image](https://user-images.githubusercontent.com/5155989/77008616-3ae57e80-6945-11ea-9b53-9d27bf99dfbe.png)
