### ISSUE TITLE
[Progress of indicator bugs]

### ISSUE THREAD

**Issue by modem7** [GimmerBot/Gimmer#72]
# Current indicator bugs progress list

## This list will be updated as issues are closed or reopened. 

List to be updated whenever a new indicator bug is found. Please @ mention @modem7 so I can see and update as necessary. 

If there are further issues that you've found with a ticket already listed below, please comment on that ticket rather than creating a separate duplicate ticket. This will help with bug tracking and resolution.

Status | Title
:-- | :--
[![badge](https://img.shields.io/github/issues/detail/s/GimmerBot/Gimmer/34.svg)](//github.com/GimmerBot/Gimmer/issues/34) | MACD is configured wrong for maximum gains
[![badge](https://img.shields.io/github/issues/detail/s/GimmerBot/Gimmer/38.svg)](//github.com/GimmerBot/Gimmer/issues/38) | Bollinger Bands don't work as desired
[![badge](https://img.shields.io/github/issues/detail/s/GimmerBot/Gimmer/35.svg)](//github.com/GimmerBot/Gimmer/issues/35) | Stochastic indicator not working
[![badge](https://img.shields.io/github/issues/detail/s/GimmerBot/Gimmer/50.svg)](//github.com/GimmerBot/Gimmer/issues/50) | EMA cross Buy/Sell operations in backtest don't correlate with TradingView signals
[![badge](https://img.shields.io/github/issues/detail/s/GimmerBot/Gimmer/51.svg)](//github.com/GimmerBot/Gimmer/issues/51) | RSI parameters for buys and sells seems to be reversed
[![badge](https://img.shields.io/github/issues/detail/s/GimmerBot/Gimmer/65.svg)](//github.com/GimmerBot/Gimmer/issues/65) | RSI buy/sells are incorrect
[![badge](https://img.shields.io/github/issues/detail/s/GimmerBot/Gimmer/66.svg)](//github.com/GimmerBot/Gimmer/issues/66) | MACD Signals are incorrect
[![badge](https://img.shields.io/github/issues/detail/s/GimmerBot/Gimmer/68.svg)](//github.com/GimmerBot/Gimmer/issues/68) | Invert Signals looks like it is backwards for all indicators
[![badge](https://img.shields.io/github/issues/detail/s/GimmerBot/Gimmer/71.svg)](//github.com/GimmerBot/Gimmer/issues/71) | Stochastic Oscillator buy/sells are incorrect
[![badge](https://img.shields.io/github/issues/detail/s/GimmerBot/Gimmer/83.svg)](//github.com/GimmerBot/Gimmer/issues/83) | Gimmer BETA v0.2.13 Bollinger Bands
[![badge](https://img.shields.io/github/issues/detail/s/GimmerBot/Gimmer/84.svg)](//github.com/GimmerBot/Gimmer/issues/84) | Persistant candle problem
[![badge](https://img.shields.io/github/issues/detail/s/GimmerBot/Gimmer/89.svg)](//github.com/GimmerBot/Gimmer/issues/89) | MACD signals aren't same as TV chart

#34, #66 seem to be duplicates as are #35, #71 and #51, #65

**Comment by MaJorDan383** [comment]
I hope they have come to an understanding of the cause of almost all of these issues.

Let's prepare a celebration cake with 1 lit candle ;)  Go team!

**Comment by modem7** [comment]
This has served its purpose. Closing
