### ISSUE TITLE
[0.2.12] Opening Gimmer twice bug

### ISSUE THREAD

**Issue by modem7** [GimmerBot/Gimmer#73]
Windows 7
v0.2.12

When opening Gimmer twice, the following error comes up

![capture](https://user-images.githubusercontent.com/4349962/40681528-4c43cedc-6381-11e8-8bb3-d9271ece3cc4.JPG)

Gimmer then opens another instance as expected.

Might be worthwhile having an option for "allow only a single instance" so that people are able to choose if they want to have two instances open (e.g. one for live trading, one for testing)

**Comment by Flllexa** [comment]
It's happen when already exists another instance opened, you need open the task manager and close when its problem appear. Is a generic problem of the Electron. 

tks
