### ISSUE TITLE
[Regression] Multiple coin pair choosing

### ISSUE THREAD

**Issue by modem7** [GimmerBot/Gimmer#74]
Request to have the feature that was available in the demo where we were able to select multiple coin pairs to be selected and monitored so that the bot can work with (I think it was) 10 pairs at once.

(I'm aware that this is being reworked, and will only be concentrated on after main release, this is more so that we have visibility of it)

Please tag as on hold, regression/feature request

**Comment by Flllexa** [comment]
It was discontinued
