### ISSUE TITLE
Buy/Sell log of signals, time values confusing

### ISSUE THREAD

**Issue by ficovolante** [GimmerBot/Gimmer#75]
#### Expected Behaviour
Display time values in log so that user can distinguish between AM and PM times. Please add AM or PM.
#### Actual Behaviour
Log entries for sell and buy actions in GUI and stdout are like:
`05-14-2018 07:00: indicator: EmaIndicator; sell ...`
#### Steps to Reproduce the Problem
Run a backtest
 - Gimmer Version: 0.2.12
 - OS: Ubuntu 18.04
 - Date: 29/5/2018

**Comment by muzkle** [comment]
Now the log have been changed to display the correct timing when things happen.

![timing-log](https://user-images.githubusercontent.com/16977637/41731962-2760b616-7556-11e8-91f7-0d794c163582.PNG)
