### ISSUE TITLE
Backtest: EMA cross Buy/Sell happens before signal shown in TV chart

### ISSUE THREAD

**Issue by ficovolante** [GimmerBot/Gimmer#76]
#### Expected Behaviour
After a backtest, TV chart should confirm that the Buy/Sell action was taken in the period after the EMA cross happened. I suggest it should happen at the opening value of that period (candle).
#### Actual Behaviour
TV chart shows Buys and Sell actions. Consistently they occur in the period before the EMA crossover i.e. one candle to the left of the crossover. Crossovers marked with yellow +
#### Steps to Reproduce the Problem
Run an EMA crossover backtest with default 9/26 periods. 30 minute period length. ETC/BTC on Binance data. Binance candles are marked every 30 mins (top and bottom of the hour) so I ensured the backtest started at the top of the hour (23:00).
#### Specifications
 - Gimmer Version: 0.2.12
 - OS: Ubuntu 18.04
 - Date: 29/5/2018
#### Screenshot
![screenshot from 2018-05-29 23-36-48](https://user-images.githubusercontent.com/39344601/40689899-4b89bf2c-639c-11e8-82e8-59cdd59e50d4.png)

Also, please note the final Sell then Buy don't happen near an EMA crossover. This might be a different issue.

**Comment by ficovolante** [comment]
Suggestion: create a debug mode, which outputs the data being used to run the backtest to the log (stdout). If this is in a form that can be imported to a spreadsheet, users can check the validity of the analysis and gain more confidence in it. For each timeframe, include OHLC data for each candle and EMAs.
Also, are you retrieving the EMA data from TV or calculating within Gimmer? Using the data from TV would give the best consistency.

**Comment by Flllexa** [comment]
Soon, we will leave the user select "open, close, high or low" to the indicator.
I see your suggestion for the Log, we want export the logs too.

Thank you man! I leave your issue opened to close when we publish in dapp this suggestions.
