### ISSUE TITLE
[0.2.13] Taskbar icon blank

### ISSUE THREAD

**Issue by modem7** [GimmerBot/Gimmer#80]
0.2.13
Windows 7

Taskbar icon is blank

![capture](https://user-images.githubusercontent.com/4349962/40798154-43fa7bc2-6502-11e8-8cc4-760f7aeeab7c.JPG)

**Comment by Flllexa** [comment]
Strange, it's ok for me, try restart the dapp or restart the OS.

![image](https://user-images.githubusercontent.com/5155989/40799560-52399d44-64e4-11e8-9b9e-8a76778eead0.png)
