### ISSUE TITLE
Search field not working on Indicator menu

### ISSUE THREAD

**Issue by keithfawcett** [GimmerBot/Gimmer#82]
Expected Behavior: Result are filtered while typing in Search field
Actual Behavior: No change to Indicator options
Steps to Reproduce the Problem: Type in the Search field of the Indicator menu
Specifications
Gimmer Version: v0.2.13
OS: Windows 7
Date: 05/31/2018

![image](https://user-images.githubusercontent.com/592055/40801490-10438efc-64e1-11e8-871e-54871bb707df.png)

**Comment by muzkle** [comment]
Filters are now working as expected for settings, indicators and safeties.
