### ISSUE TITLE
Gimmer BETA v0.2.13 Bollinger Bands 

### ISSUE THREAD

**Issue by Drangla** [GimmerBot/Gimmer#83]
#### Expected Behaviour
Buy at the lower Band, sell at the upper Band 
#### Actual Behaviour
Buy at the upper Band, sell at the lower Band
#### Steps to Reproduce the Problem
invert the signal :-) 
#### Specifications
 - Gimmer Version: v0.2.13
 - OS: Windows 10
 - Date: 31.05.2018
 
#### Printscreen (Case needed)
![unbenannt](https://user-images.githubusercontent.com/35429030/40803084-e40c7d94-6517-11e8-8f34-4e58b19e9469.PNG)

**Comment by Flllexa** [comment]
The default configuration is more profitable, if the user want he can to invert the signal ;)

Tks man

**Comment by keithfawcett** [comment]
Hi @Flllexa, the default value should have nothing to do with profitability and should not be changed from the expected way it functions in any other system. It has to do with the way the indicator is expected to function by default.  By default, the Bollinger Band indicator is expected to sell at the top of the band and buy at the bottom of the band and this should happen WITHOUT selecting "Invert Signal". If you invert the signal you would expect for the indicator to function in reverse of the DEFAULT behavior -- meaing that it would buy at the top of the band and sell at the bottom of the band.
