### ISSUE TITLE
Hide the "Running Simulation" button unless on the "Running & Activity" view.

### ISSUE THREAD

**Issue by keithfawcett** [GimmerBot/Gimmer#85]
Expected Behavior: The "Running Simulation" button should only be visible on the "Running & Activity" view. This is confusing. 
Actual Behavior: Button is available on "Strategy & Backtesting" view. 
Steps to Reproduce the Problem: N/A

Specifications
Gimmer Version: v0.2.13
OS: Windows 7
Date: 05/31/2018

![image](https://user-images.githubusercontent.com/592055/40810406-a78af66e-64fb-11e8-8183-8cc09d05d6f9.png)

**Comment by muzkle** [comment]
This item now only is visible on the "Running & Activity" page as you can see on the image below:

![strategy-header-2](https://user-images.githubusercontent.com/16977637/41621350-c1b76748-73e2-11e8-859e-1abb67bd1e1e.PNG)
