### ISSUE TITLE
Hide the "Options" button/menu on the "Running & Activity" view.

### ISSUE THREAD

**Issue by keithfawcett** [GimmerBot/Gimmer#86]
Expected Behavior: The "Options" button/menu should only be visible on the "Strategy & Backtesting" view. Not on the "Running & Activity" view. This is confusing. 
Actual Behavior: Button is available on "Running & Activity" view. 
Steps to Reproduce the Problem: N/A

Specifications
Gimmer Version: v0.2.13
OS: Windows 7
Date: 05/31/2018

![image](https://user-images.githubusercontent.com/592055/40810515-f7b66a10-64fb-11e8-8677-921a0543cc7e.png)

**Comment by muzkle** [comment]
Options button have been hidden from the "Running & Acitivity" page.
It is only visible now at "strategy & Backtest".
![strategy-header-1](https://user-images.githubusercontent.com/16977637/41621304-9f3afe5a-73e2-11e8-8b42-cada80b63af6.PNG)
