### ISSUE TITLE
Bittrex exchange icon broken on "Running & Activity" view

### ISSUE THREAD

**Issue by keithfawcett** [GimmerBot/Gimmer#88]
Expected Behavior: Icon should show
Actual Behavior: Broken icon
Steps to Reproduce the Problem: Use Bittrex and go to "Running & Activity" view

Specifications
Gimmer Version: v0.2.13
OS: Windows 7
Date: 06/01/2018

![image](https://user-images.githubusercontent.com/592055/40848135-4e454c80-658c-11e8-9a1a-5f3e8ce95cf2.png)

**Comment by muzkle** [comment]
Icon fixed.

![bittrext-icon](https://user-images.githubusercontent.com/16977637/41621205-6f5b7ba6-73e2-11e8-9eae-816b709c6c7c.PNG)
