### ISSUE TITLE
[0.2.0] Can drag and drop files onto Gimmer

### ISSUE THREAD

**Issue by modem7** [GimmerBot/Gimmer#9]
Windows 7 x64
Gimmer 0.2.0

You are able to drag and drop any file into gimmer and it attempts to process them, shortly crashing afterwards. 

![capture](https://user-images.githubusercontent.com/4349962/40137502-7a7613da-5942-11e8-990d-094f5d8f344e.JPG)
![capture2](https://user-images.githubusercontent.com/4349962/40137503-7a97442e-5942-11e8-95b6-9cc9c5b73162.JPG)

**Comment by rafagimmer** [comment]
Thanks for your info, we are already working to solve the problem.

**Comment by modem7** [comment]
Have moved onto other projects. Closing this unless someone requires this functionality.
