### ISSUE TITLE
[0.2.13] UX Improvements on Running and activity

### ISSUE THREAD

**Issue by modem7** [GimmerBot/Gimmer#91]
1. Edit button seems to not have any use in running and activity currently
2. Icon is not showing for exchange
3. Recommending being able to change start balance on simulation

 - Gimmer Version: 0.2.13
 - OS: Windows 7
 
![capture](https://user-images.githubusercontent.com/4349962/40992548-08ec9e66-68ef-11e8-877c-cc48ee487ee3.JPG)

**Comment by muzkle** [comment]
Changed the UI as suggested, right now it is:

1- Options button only on the "Strategy & Backtest" page with a different color, so people can see it better:
![strategy-header-1](https://user-images.githubusercontent.com/16977637/41621094-11c2c9fe-73e2-11e8-843e-238b05094aa7.PNG)

2- Start strategy as live or simulation is now under the "Running & Activity" page:
![strategy-header-2](https://user-images.githubusercontent.com/16977637/41621125-2a000dd8-73e2-11e8-95a8-12eb7ddd49cb.PNG)
