### ISSUE TITLE
Bots execute a FOMO sell

### ISSUE THREAD

**Issue by Crypto-Ferret** [GimmerBot/Gimmer#94]
#### Expected Behaviour
Bots to hold coins until sentiment is at a sell.
#### Actual Behaviour
Bot starts and executes a sell order if holding the base coin (in this case TRX) regardless of the buy/sell sentiment.
#### Steps to Reproduce the Problem
trade live holding alt coin on Binance.
#### Specifications
 - Gimmer Version: 0.2.14
 - OS: WIN 10
 - Date: 14/06/18
 
#### Printscreen (Case needed)
![fomo sell](https://user-images.githubusercontent.com/39388970/41404641-a5646eb4-6fbf-11e8-82b2-383d1314ccd8.JPG)

**Comment by Flllexa** [comment]
The period 5 minutes changes is very fast, we are checking that sentiment have delay. I will leave opened for we check the sentiment.

**Comment by Flllexa** [comment]
It was fixed in 1.7.7 version
