### ISSUE TITLE
Not reacting on HMA sale signal

### ISSUE THREAD

**Issue by johnyqi** [GimmerBot/Gimmer#95]
#### Expected Behaviour
Sell on HMA cross. 
#### Actual Behaviour
If you check the last candle, there is a clear signal to sell, but Gimmer didnt react so I had to go out manually.
#### Steps to Reproduce the Problem
Trade EOS USDT pair 1 hour interval, HMA 26/9, invert signal
#### Specifications
 - Gimmer Version: 0.2.13
 - OS: OSX
 - Date: 14 June
 
#### Printscreen (Case needed)
<img width="1544" alt="screenshot 2018-06-14 15 16 24" src="https://user-images.githubusercontent.com/36193495/41414436-50e83268-6fe6-11e8-8b4e-233bd6f09b38.png">

**Comment by Flllexa** [comment]
We already identified this problem, for sample, one bot that run with period 1h, the tick is 1h per 1h, but the candle can to mount first, I will update for tick in realtime using the period correctly.

Tks, we already focused in solve this problem.

**Comment by johnyqi** [comment]
Have to say I have no idea what Gimmer does with HMA. Often it doesn't react on a clear sell signal, while here, it bought and sold within few minutes, while HMA showed no changes, no crossings. If simple things are not working I really don't know how we can build complex strategies with these indicators. Something is fundamentally wrong with them.

<img width="876" alt="screenshot 2018-06-16 09 50 28" src="https://user-images.githubusercontent.com/36193495/41496920-0f653ed8-714b-11e8-97e3-e15b1b15be5b.png">

**Comment by johnyqi** [comment]
To clarify, the Buy signal is late because I started bot late, but Sell signal makes no sense.

**Comment by Flllexa** [comment]
In the matter of the delay in buys and sells we have already resolved.
I'm running my strategy working normally. 
The problems you have reported I'll leave one bot running here to verify.

Thanks

**Comment by johnyqi** [comment]
This is not delay issue. Im running a simple HMA strategy, buy when slow line goes below fast line. As you can see from screenshots, Buy and Sell signals are all over the place, make absolutely no sense.
<img width="876" alt="screenshot 2018-06-16 09 50 28" src="https://user-images.githubusercontent.com/36193495/41505581-549c74aa-720c-11e8-9427-14992cab367f.png">
<img width="1853" alt="screenshot 2018-06-16 11 28 49" src="https://user-images.githubusercontent.com/36193495/41505582-54b2ddf8-720c-11e8-8615-063443cfc0cf.png">
<img width="681" alt="screenshot 2018-06-16 15 41 21" src="https://user-images.githubusercontent.com/36193495/41505583-54c8dbee-720c-11e8-8b22-b9e783f89933.png">
<img width="1050" alt="screenshot 2018-06-16 15 52 10" src="https://user-images.githubusercontent.com/36193495/41505584-54e0137c-720c-11e8-8fc7-7d28e754340f.png">
<img width="745" alt="screenshot 2018-06-16 15 57 29" src="https://user-images.githubusercontent.com/36193495/41505585-54f6d71a-720c-11e8-8994-ebe4ab62d15f.png">
<img width="1049" alt="screenshot 2018-06-16 16 37 48" src="https://user-images.githubusercontent.com/36193495/41505586-550e71ea-720c-11e8-9625-b299d2cc610f.png">

**Comment by johnyqi** [comment]
And then, in this case, it should also buy when slow goes under below, while RSI is above 50%. RSI condition is met, but HMA is not.

HMA is clearly NOT working and it will cost people's money if they run any strategy with HMA.

<img in width="1056" alt="screenshot 2018-06-17 08 55 05" src="https://user-images.githubusercontent.com/36193495/41505612-ce999c9c-720c-11e8-9991-e37c0a154e5a.png">

**Comment by johnyqi** [comment]
And I have to add, in backtesting I don't encounter so many issues, obviously something is terribly wrong with live trading

**Comment by johnyqi** [comment]
Here is a head to head comparison, on the left side, is live trading, on the right side is backtesting, same settings, same period. Backtesting works fine, it doesn't trigger Buy because slow line is above fast line, while in live trading Gimmer is going all over the place. The app is unusable so I'm waiting until live trading is fixed.

<img width="1814" alt="screenshot 2018-06-17 10 09 39" src="https://user-images.githubusercontent.com/36193495/41506067-c581d23c-7216-11e8-8139-100372c89b2f.png">

**Comment by Flllexa** [comment]
I already know your problem, you are editing the bot, and not restart the bot running, is necessary stop and start again to running bot get the new configurations, I will put one alert to advise the users for restart the bot when they update the strategy.

**Comment by johnyqi** [comment]
Ok, I was wondering about that. Will try again.

**Comment by modem7** [comment]
That's sounds very counter-intuitive. 

The bot needs to do this automatically, not relying on user to remember 300 different things they need to do to get it working properly. 

Gimmer is/was supposed to be intuitive for people who have little to medium knowledge of trading. They really shouldn't need to know trading + coding + UX design + whatever else is required. This is definitely a bug that needs to be resolved using automation, not relying on human interaction.

**Comment by johnyqi** [comment]
I'm simply not convinced that HMA is working properly. Look this situation, clear breakout, slow HMA is below fast one, the situation is clear as day, but Gimmer does nothing.

<img width="1061" alt="screenshot 2018-06-18 10 34 46" src="https://user-images.githubusercontent.com/36193495/41526167-a6888466-72e3-11e8-8a5b-55e91e8b8227.png">
