### ISSUE TITLE
Direct link to Running & Activity

### ISSUE THREAD

**Issue by johnyqi** [GimmerBot/Gimmer#97]
When clicking on bots we should have an option to go to Running & Activity page directly, without going through Strategy and Backtest.

**Comment by cycletrader** [comment]
Maybe a simple default selection in settings would be a simple solution, that way people can choose their default opening context

**Comment by muzkle** [comment]
I have included 2 buttons now:

1- Always will have a Backtest button that will lead the user intot he Strategy/Backtest page
2- Once a strategy is running, it will display a new button on the side of the Backtest buttons labeled as "Activity" and will jump straight into the activities page.

![activity-button](https://user-images.githubusercontent.com/16977637/41615294-3a477a16-73d1-11e8-9621-d0a30f55bc00.PNG)

Will be released on the next version.

**Comment by johnyqi** [comment]
Neat :-)
