### ISSUE TITLE
RSI not triggering properly

### ISSUE THREAD

**Issue by johnyqi** [GimmerBot/Gimmer#99]
#### Expected Behaviour
Buy below 30%, sell above 70%
#### Actual Behaviour
Buy and sell is delayed
#### Steps to Reproduce the Problem
RSI standard settings, no invert, BTC USDT pair, 1 hour, at beginning of April
#### Specifications
 - Gimmer Version: 0.2.14
 - OS: OSX
 - Date: 15. April
 
#### Printscreen (Case needed)
<img width="2048" alt="screenshot 2018-06-15 16 00 58" src="https://user-images.githubusercontent.com/36193495/41472244-2282f8b0-70b6-11e8-856f-e28771cabc66.png">

**Comment by Flllexa** [comment]
Check if you added a configuration in tradingview different of the indicator configuration, I show a sample in image bellow:

![image](https://user-images.githubusercontent.com/5155989/41487372-e0da0c92-70be-11e8-9cce-318099eed7cf.png)

Take a screenshot following my sample and describe your steps for that we can reproduce here.

**Comment by johnyqi** [comment]
Configuration is the same, 14 & 14
